# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
    ]
